# C++ Patterns and Snippets

Collection of modern (C++17/C++20) C++ patterns and snippets and some standard patterns.
The code labeled C++17 will probably use no specific C++17 features and can be compiled with earlier standards, but this is not tested.

## Testing in Compiler Explorer

https://compiler-explorer.com/z/zYbf6dxjP

### Useful Compiler Options 

clang/gcc:

----
-std=c++20 -Os -Wall -Wextra -Wpedantic -Wshadow -Wstrict-aliasing -Wconversion -Wsign-conversion -Wnull-dereference -Wno-format-security
----

MSVC

----
/std:c++20 /W4
----  

### Simple log function which can be switched off to generate no logging code

[source,C++]
----
#include <cstdio>
#include <utility>

template <typename... Args>
inline void log(const char* msg, [[maybe_unused]] Args&&... args) noexcept {
    static constexpr bool enable = true;
    if constexpr (enable) {
        std::printf(msg, std::forward<Args>(args)...);
        std::printf("\n");
    }
}

int main() {

    log( "hello %s\n", "world");
    return 0;
}

----


## Consteval Value (C++ 20)

https://compiler-explorer.com/z/d6KcrKede

    targets/consteval_value

* Using a non type template parameter as value at compile time
* Providing compile time values from build in types and custom types
* Ensure compile time evaluation

## Inside Copy Swap Idiom (C++ 17)

https://compiler-explorer.com/z/6e8P33vGv

    targets/inside_copy_swap_idiom

* implementing swap
* Using the copy swap idiom to implement copy and move assignment

## Object Layout Deduction (C++ 17)

https://compiler-explorer.com/z/PxME3r11W

    targets/object_layout_deduction

* Instantiating different versions of a class depending on the construction
* Putting extra parts in the different versions(methods, fields)
* Having a common part which is shared

## Transient Proxy using RTTY (C++ 20)

https://compiler-explorer.com/z/TjWTTbPhr

    targets/transient_proxy_rtty

* type erase a reference via RTTY to be transferred type safe across ABI boundaries
* function traits implementation

## Type Literals (C++ 20)

https://compiler-explorer.com/z/8Kq8Tcreh

    targets/type_literals

* using C++ 20 string literal operator template to generate a type without data+ 
  https://en.cppreference.com/w/cpp/language/user_literal
* Converting the type literal to std::array and std::string_view 
* output the generated type info at compile time with [[deprecated]] warnings


## Latest Drafts of the C++ Standard

### C++ 17

https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/n4713.pdf

### C++ 20

https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/n4878.pdf